//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITRUS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_FloorThickness {
            get {
                return ((string)(this["FSCRT1_FloorThickness"]));
            }
            set {
                this["FSCRT1_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_RebarOutlets {
            get {
                return ((string)(this["FSCRT1_RebarOutlets"]));
            }
            set {
                this["FSCRT1_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT1_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT1_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT1_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT1_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT1_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT1_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT1_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT1_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT1_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT1_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT1_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT1_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_FloorThickness {
            get {
                return ((string)(this["FSCRT2_FloorThickness"]));
            }
            set {
                this["FSCRT2_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_RebarOutlets {
            get {
                return ((string)(this["FSCRT2_RebarOutlets"]));
            }
            set {
                this["FSCRT2_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT2_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT2_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT2_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT2_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT2_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT2_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT2_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT2_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT2_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT2_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT2_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT2_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT2_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT2_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_FloorThickness {
            get {
                return ((string)(this["FSCRT3_FloorThickness"]));
            }
            set {
                this["FSCRT3_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_RebarOutlets {
            get {
                return ((string)(this["FSCRT3_RebarOutlets"]));
            }
            set {
                this["FSCRT3_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT3_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT3_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT3_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT3_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT3_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT3_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT3_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT3_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT3_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT3_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT3_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT3_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT3_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT3_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_FloorThickness {
            get {
                return ((string)(this["FSCRT4_FloorThickness"]));
            }
            set {
                this["FSCRT4_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_RebarOutlets {
            get {
                return ((string)(this["FSCRT4_RebarOutlets"]));
            }
            set {
                this["FSCRT4_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT4_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT4_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT4_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT4_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT4_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT4_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT4_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT4_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT4_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT4_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT4_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT4_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT4_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT4_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondLowerRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondLowerRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondLowerRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondTopRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondTopRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondTopRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondLeftRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondLeftRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondLeftRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondRightRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondRightRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondRightRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_FloorThickness {
            get {
                return ((string)(this["FSCRT5_FloorThickness"]));
            }
            set {
                this["FSCRT5_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_RebarOutlets {
            get {
                return ((string)(this["FSCRT5_RebarOutlets"]));
            }
            set {
                this["FSCRT5_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT5_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT5_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT5_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT5_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT5_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT5_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT5_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT5_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT5_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT5_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT5_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT5_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT5_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT5_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondLowerRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondLowerRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondLowerRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondTopRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondTopRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondTopRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondLeftRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondLeftRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondLeftRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondRightRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondRightRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondRightRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_FloorThickness {
            get {
                return ((string)(this["FSCRT6_FloorThickness"]));
            }
            set {
                this["FSCRT6_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_RebarOutlets {
            get {
                return ((string)(this["FSCRT6_RebarOutlets"]));
            }
            set {
                this["FSCRT6_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT6_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT6_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT6_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT6_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT6_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT6_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT6_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT6_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT6_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT6_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT6_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT6_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT6_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT6_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLowerRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondLowerRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondLowerRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondTopRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondTopRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondTopRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLeftRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondLeftRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondLeftRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondRightRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondRightRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondRightRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLowerRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondLowerRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondLowerRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondTopRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondTopRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondTopRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLeftRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondLeftRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondLeftRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondRightRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondRightRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondRightRebarOffset2"] = value;
            }
        }
    }
}
