//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITRUS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_FloorThickness {
            get {
                return ((string)(this["FSCRT1_FloorThickness"]));
            }
            set {
                this["FSCRT1_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_RebarOutlets {
            get {
                return ((string)(this["FSCRT1_RebarOutlets"]));
            }
            set {
                this["FSCRT1_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT1_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT1_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT1_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT1_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT1_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT1_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT1_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT1_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT1_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT1_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT1_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT1_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT1_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_FloorThickness {
            get {
                return ((string)(this["FSCRT2_FloorThickness"]));
            }
            set {
                this["FSCRT2_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_RebarOutlets {
            get {
                return ((string)(this["FSCRT2_RebarOutlets"]));
            }
            set {
                this["FSCRT2_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT2_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT2_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT2_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT2_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT2_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT2_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT2_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT2_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT2_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT2_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT2_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT2_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT2_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT2_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT2_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_FloorThickness {
            get {
                return ((string)(this["FSCRT3_FloorThickness"]));
            }
            set {
                this["FSCRT3_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_RebarOutlets {
            get {
                return ((string)(this["FSCRT3_RebarOutlets"]));
            }
            set {
                this["FSCRT3_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT3_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT3_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT3_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT3_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT3_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT3_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT3_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT3_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT3_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT3_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT3_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT3_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT3_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT3_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT3_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_FloorThickness {
            get {
                return ((string)(this["FSCRT4_FloorThickness"]));
            }
            set {
                this["FSCRT4_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_RebarOutlets {
            get {
                return ((string)(this["FSCRT4_RebarOutlets"]));
            }
            set {
                this["FSCRT4_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT4_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT4_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT4_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT4_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT4_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT4_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT4_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT4_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT4_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT4_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT4_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT4_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT4_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT4_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondLowerRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondLowerRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondLowerRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondTopRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondTopRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondTopRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondLeftRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondLeftRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondLeftRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT4_SecondRightRebarOffset {
            get {
                return ((string)(this["FSCRT4_SecondRightRebarOffset"]));
            }
            set {
                this["FSCRT4_SecondRightRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_FloorThickness {
            get {
                return ((string)(this["FSCRT5_FloorThickness"]));
            }
            set {
                this["FSCRT5_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_RebarOutlets {
            get {
                return ((string)(this["FSCRT5_RebarOutlets"]));
            }
            set {
                this["FSCRT5_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT5_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT5_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT5_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT5_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT5_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT5_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT5_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT5_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT5_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT5_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT5_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT5_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT5_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT5_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondLowerRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondLowerRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondLowerRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondTopRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondTopRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondTopRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondLeftRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondLeftRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondLeftRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT5_SecondRightRebarOffset {
            get {
                return ((string)(this["FSCRT5_SecondRightRebarOffset"]));
            }
            set {
                this["FSCRT5_SecondRightRebarOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_FloorThickness {
            get {
                return ((string)(this["FSCRT6_FloorThickness"]));
            }
            set {
                this["FSCRT6_FloorThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_RebarOutlets {
            get {
                return ((string)(this["FSCRT6_RebarOutlets"]));
            }
            set {
                this["FSCRT6_RebarOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_RebarSecondOutlets {
            get {
                return ((string)(this["FSCRT6_RebarSecondOutlets"]));
            }
            set {
                this["FSCRT6_RebarSecondOutlets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_FirstStirrupOffset {
            get {
                return ((string)(this["FSCRT6_FirstStirrupOffset"]));
            }
            set {
                this["FSCRT6_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_IncreasedStirrupSpacing {
            get {
                return ((string)(this["FSCRT6_IncreasedStirrupSpacing"]));
            }
            set {
                this["FSCRT6_IncreasedStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_StandardStirrupSpacing {
            get {
                return ((string)(this["FSCRT6_StandardStirrupSpacing"]));
            }
            set {
                this["FSCRT6_StandardStirrupSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["FSCRT6_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["FSCRT6_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_ColumnSectionOffset {
            get {
                return ((string)(this["FSCRT6_ColumnSectionOffset"]));
            }
            set {
                this["FSCRT6_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_DeepeningBarsSize {
            get {
                return ((string)(this["FSCRT6_DeepeningBarsSize"]));
            }
            set {
                this["FSCRT6_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLowerRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondLowerRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondLowerRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondTopRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondTopRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondTopRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLeftRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondLeftRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondLeftRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondRightRebarOffset1 {
            get {
                return ((string)(this["FSCRT6_SecondRightRebarOffset1"]));
            }
            set {
                this["FSCRT6_SecondRightRebarOffset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLowerRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondLowerRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondLowerRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondTopRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondTopRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondTopRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondLeftRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondLeftRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondLeftRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSCRT6_SecondRightRebarOffset2 {
            get {
                return ((string)(this["FSCRT6_SecondRightRebarOffset2"]));
            }
            set {
                this["FSCRT6_SecondRightRebarOffset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_NumberOfBarsLRFaces {
            get {
                return ((string)(this["RCRF_NumberOfBarsLRFaces"]));
            }
            set {
                this["RCRF_NumberOfBarsLRFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_NumberOfBarsTBFaces {
            get {
                return ((string)(this["RCRF_NumberOfBarsTBFaces"]));
            }
            set {
                this["RCRF_NumberOfBarsTBFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_RebarOutletsLengthLong {
            get {
                return ((string)(this["RCRF_RebarOutletsLengthLong"]));
            }
            set {
                this["RCRF_RebarOutletsLengthLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_RebarOutletsLengthShort {
            get {
                return ((string)(this["RCRF_RebarOutletsLengthShort"]));
            }
            set {
                this["RCRF_RebarOutletsLengthShort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_FloorThicknessAboveColumn {
            get {
                return ((string)(this["RCRF_FloorThicknessAboveColumn"]));
            }
            set {
                this["RCRF_FloorThicknessAboveColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_StandardStirrupStep {
            get {
                return ((string)(this["RCRF_StandardStirrupStep"]));
            }
            set {
                this["RCRF_StandardStirrupStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_IncreasedStirrupStep {
            get {
                return ((string)(this["RCRF_IncreasedStirrupStep"]));
            }
            set {
                this["RCRF_IncreasedStirrupStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_FirstStirrupOffset {
            get {
                return ((string)(this["RCRF_FirstStirrupOffset"]));
            }
            set {
                this["RCRF_FirstStirrupOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_StirrupIncreasedPlacementHeight {
            get {
                return ((string)(this["RCRF_StirrupIncreasedPlacementHeight"]));
            }
            set {
                this["RCRF_StirrupIncreasedPlacementHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_ColumnSectionOffset {
            get {
                return ((string)(this["RCRF_ColumnSectionOffset"]));
            }
            set {
                this["RCRF_ColumnSectionOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCRF_DeepeningBarsSize {
            get {
                return ((string)(this["RCRF_DeepeningBarsSize"]));
            }
            set {
                this["RCRF_DeepeningBarsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_ExtensionLeftLenghtL1 {
            get {
                return ((string)(this["BRF_ExtensionLeftLenghtL1"]));
            }
            set {
                this["BRF_ExtensionLeftLenghtL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_ExtensionLeftLenghtL2 {
            get {
                return ((string)(this["BRF_ExtensionLeftLenghtL2"]));
            }
            set {
                this["BRF_ExtensionLeftLenghtL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_ExtensionRightLenghtR1 {
            get {
                return ((string)(this["BRF_ExtensionRightLenghtR1"]));
            }
            set {
                this["BRF_ExtensionRightLenghtR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_ExtensionRightLenghtR2 {
            get {
                return ((string)(this["BRF_ExtensionRightLenghtR2"]));
            }
            set {
                this["BRF_ExtensionRightLenghtR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_DeepeningIntoTheStructureL1 {
            get {
                return ((string)(this["BRF_DeepeningIntoTheStructureL1"]));
            }
            set {
                this["BRF_DeepeningIntoTheStructureL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_DeepeningIntoTheStructureL2 {
            get {
                return ((string)(this["BRF_DeepeningIntoTheStructureL2"]));
            }
            set {
                this["BRF_DeepeningIntoTheStructureL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_DeepeningIntoTheStructureR1 {
            get {
                return ((string)(this["BRF_DeepeningIntoTheStructureR1"]));
            }
            set {
                this["BRF_DeepeningIntoTheStructureR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_DeepeningIntoTheStructureR2 {
            get {
                return ((string)(this["BRF_DeepeningIntoTheStructureR2"]));
            }
            set {
                this["BRF_DeepeningIntoTheStructureR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_StirrupIndentL1 {
            get {
                return ((string)(this["BRF_StirrupIndentL1"]));
            }
            set {
                this["BRF_StirrupIndentL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_StirrupStepL1 {
            get {
                return ((string)(this["BRF_StirrupStepL1"]));
            }
            set {
                this["BRF_StirrupStepL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_StirrupIndentR1 {
            get {
                return ((string)(this["BRF_StirrupIndentR1"]));
            }
            set {
                this["BRF_StirrupIndentR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_StirrupStepR1 {
            get {
                return ((string)(this["BRF_StirrupStepR1"]));
            }
            set {
                this["BRF_StirrupStepR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_StirrupStepC1 {
            get {
                return ((string)(this["BRF_StirrupStepC1"]));
            }
            set {
                this["BRF_StirrupStepC1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_ExtensionAddBarL2 {
            get {
                return ((string)(this["BRF_ExtensionAddBarL2"]));
            }
            set {
                this["BRF_ExtensionAddBarL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_ExtensionAddBarR2 {
            get {
                return ((string)(this["BRF_ExtensionAddBarR2"]));
            }
            set {
                this["BRF_ExtensionAddBarR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_NumberOfBarsTopFaces {
            get {
                return ((string)(this["BRF_NumberOfBarsTopFaces"]));
            }
            set {
                this["BRF_NumberOfBarsTopFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BRF_NumberOfBarsBottomFaces {
            get {
                return ((string)(this["BRF_NumberOfBarsBottomFaces"]));
            }
            set {
                this["BRF_NumberOfBarsBottomFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StepRebarCoverLayer {
            get {
                return ((string)(this["SFRF_StepRebarCoverLayer"]));
            }
            set {
                this["SFRF_StepRebarCoverLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StepLength {
            get {
                return ((string)(this["SFRF_StepLength"]));
            }
            set {
                this["SFRF_StepLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StepHeight {
            get {
                return ((string)(this["SFRF_StepHeight"]));
            }
            set {
                this["SFRF_StepHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StaircaseSlabThickness {
            get {
                return ((string)(this["SFRF_StaircaseSlabThickness"]));
            }
            set {
                this["SFRF_StaircaseSlabThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StairCoverLayer {
            get {
                return ((string)(this["SFRF_StairCoverLayer"]));
            }
            set {
                this["SFRF_StairCoverLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StepRebarStep {
            get {
                return ((string)(this["SFRF_StepRebarStep"]));
            }
            set {
                this["SFRF_StepRebarStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_StaircaseRebarStep {
            get {
                return ((string)(this["SFRF_StaircaseRebarStep"]));
            }
            set {
                this["SFRF_StaircaseRebarStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_TopExtensionStaircase {
            get {
                return ((string)(this["SFRF_TopExtensionStaircase"]));
            }
            set {
                this["SFRF_TopExtensionStaircase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_TopExtensionHeightStaircase {
            get {
                return ((string)(this["SFRF_TopExtensionHeightStaircase"]));
            }
            set {
                this["SFRF_TopExtensionHeightStaircase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_BottomExtensionHeightStaircase {
            get {
                return ((string)(this["SFRF_BottomExtensionHeightStaircase"]));
            }
            set {
                this["SFRF_BottomExtensionHeightStaircase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_BottomExtensionHeightStaircaseNodeA2 {
            get {
                return ((string)(this["SFRF_BottomExtensionHeightStaircaseNodeA2"]));
            }
            set {
                this["SFRF_BottomExtensionHeightStaircaseNodeA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_FirstBarMeshName {
            get {
                return ((string)(this["SFRF_FirstBarMeshName"]));
            }
            set {
                this["SFRF_FirstBarMeshName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_AdditionalBarMeshName_1 {
            get {
                return ((string)(this["SFRF_AdditionalBarMeshName_1"]));
            }
            set {
                this["SFRF_AdditionalBarMeshName_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SFRF_AdditionalBarMeshName_2 {
            get {
                return ((string)(this["SFRF_AdditionalBarMeshName_2"]));
            }
            set {
                this["SFRF_AdditionalBarMeshName_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_BottomXDirectionRebarSpacing {
            get {
                return ((string)(this["SR_BottomXDirectionRebarSpacing"]));
            }
            set {
                this["SR_BottomXDirectionRebarSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_BottomYDirectionRebarSpacing {
            get {
                return ((string)(this["SR_BottomYDirectionRebarSpacing"]));
            }
            set {
                this["SR_BottomYDirectionRebarSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_TopXDirectionRebarSpacing {
            get {
                return ((string)(this["SR_TopXDirectionRebarSpacing"]));
            }
            set {
                this["SR_TopXDirectionRebarSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_TopYDirectionRebarSpacing {
            get {
                return ((string)(this["SR_TopYDirectionRebarSpacing"]));
            }
            set {
                this["SR_TopYDirectionRebarSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_PerimeterFramingDiam {
            get {
                return ((string)(this["SR_PerimeterFramingDiam"]));
            }
            set {
                this["SR_PerimeterFramingDiam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_PerimeterFramingAnchoring {
            get {
                return ((string)(this["SR_PerimeterFramingAnchoring"]));
            }
            set {
                this["SR_PerimeterFramingAnchoring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_PerimeterFramingEndCoverLayer {
            get {
                return ((string)(this["SR_PerimeterFramingEndCoverLayer"]));
            }
            set {
                this["SR_PerimeterFramingEndCoverLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SR_PerimeterFramingStep {
            get {
                return ((string)(this["SR_PerimeterFramingStep"]));
            }
            set {
                this["SR_PerimeterFramingStep"] = value;
            }
        }
    }
}
